name: CosmoML
channels:
- pytorch
- defaults
- conda-forge
- nvidia
dependencies:
- pytorch
- torchvision
- pytorch-cuda=12.1
- scipy
- visdom
- jsonpatch
- matplotlib
- pip
- pip:
  - dominate
  - Pillow
  - numpy
  - packaging
  - GPUtil
  - Pylians
